[dependencies]
  sonyflake = { git = "https://github.com/ystyle/cj-sonyflake", branch = "master"}
  multipart = { git = "https://gitcode.com/Cangjie-SIG/multipart", branch = "0.1.3" }

[package]
  cjc-version = "0.59.6"
  compile-option = "-Woff unused"
  description = "一个轻量级的web框架"
  link-option = ""
  name = "tang"
  output-type = "static"
  src-dir = "src"
  target-dir = ""
  version = "1.0.0"

[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = [ "${CANGJIE_STDX_PATH}" ]

[profile.build]
incremental = false