[package]
  cjc-version = "1.0.0"
  name = "demo"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = "--static -O2"
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]


[target.x86_64-unknown-linux-gnu.bin-dependencies]
  path-option = [ "${CANGJIE_STDX_PATH}" ]
